### ISSUE TITLE
All pams seeds are wheat seeds to hwyla

### ISSUE THREAD

**Issue by IchigoGames** [MatrexsVigil/phc2foodcore#4]
all pams seeds show up as wheat seeds on hwyla 

Minecraft 1.15.2
Forge 31.1.50
pamhc2crops-1.15.2-1.0.3

https://github.com/TehNut/HWYLA/issues/244#event-3285914529 reported here first but he said it
was a pams issue.

**Comment by Linguardium** [comment]
Can't reproduce with foodcore alone (since the seeds are added by another mod)
this is caused by waila/hwyla using getitemseeds, which defaults to wheat seeds (and pam did not override this method)
I believe i fixed this for the relevent mod and suggest this is closed here since it does not apply.
