### ISSUE TITLE
smoresitem lang entry duplicated

### ISSUE THREAD

**Issue by Linguardium** [MatrexsVigil/phc2foodcore#6]
https://github.com/MatrexsVigil/phc2foodcore/blob/88cfd3cb7011e1e9177fafbc639362d5473a4d3f/src/main/resources/assets/pamhc2foodcore/lang/en_us.json#L165

may cause confusion in future updating or translating.

**Comment by MatrexsVigil** [comment]
Thanks for letting me know!
